### ISSUE TITLE
Segmentation fault when executing /usr/bin/getent

### ISSUE THREAD

**Issue by Cycatz** [Cycatz/nss-host2ips#1]
```
$ sudo coredumpctl debug  /usr/bin/getent           
          PID: 893988 (getent)
           UID: 1000 (cycatz)
           GID: 1000 (cycatz)
        Signal: 11 (SEGV)
     Timestamp: Sat 2023-01-28 00:42:25 CST (2 days ago)
  Command Line: getent hosts
    Executable: /usr/bin/getent
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (cycatz)
       Boot ID: ee455e767b6e4874a7a9da8069c5e340
    Machine ID: 6c03f7a4927e4eedb6a74a6f1c3f7633
      Hostname: air.staque.xyz
       Storage: /var/lib/systemd/coredump/core.getent.1000.ee455e767b6e4874a7a9da8069c5e340.893988.1674888145000000.zst (present)
  Size on Disk: 47.3K
       Message: Process 893988 (getent) of user 1000 dumped core.

                Module libnss_host2ips.so.2 without build-id.
                Stack trace of thread 893988:
                #0  0x00007fe322598301 nss_host2ips_free_host_list (libnss_host2ips.so.2 + 0x1301)
                #1  0x00007fe322598745 _nss_host2ips_endhostent_locked (libnss_host2ips.so.2 + 0x1745)
                #2  0x00007fe322598773 _nss_host2ips_endhostent (libnss_host2ips.so.2 + 0x1773)
                #3  0x00007fe3226d15cb __nss_endent (libc.so.6 + 0x1325cb)
                #4  0x00007fe3226b82b3 endhostent (libc.so.6 + 0x1192b3)
                #5  0x00005558b13c8339 hosts_keys (getent + 0x4339)
                #6  0x00005558b13c7109 main (getent + 0x3109)
                #7  0x00007fe3225c2290 __libc_start_call_main (libc.so.6 + 0x23290)
                #8  0x00007fe3225c234a __libc_start_main_impl (libc.so.6 + 0x2334a)
                #9  0x00005558b13c71d5 _start (getent + 0x31d5)
                ELF object binary architecture: AMD x86-64
```

```
(gdb) bt
#0  0x00007fe322598301 in nss_host2ips_free_host_list (host_list=0x5558b332b8b0) at src/parser.c:45
#1  0x00007fe322598745 in _nss_host2ips_endhostent_locked () at src/hosts.c:114
#2  0x00007fe322598773 in _nss_host2ips_endhostent () at src/hosts.c:124
#3  0x00007fe3226d15cb in __nss_endent (func_name=func_name@entry=0x7fe32273a251 "endhostent", lookup_fct=<optimized out>,
    nip=nip@entry=0x7fe32277fb80 <nip>, startp=startp@entry=0x7fe32277fb70 <startp>, last_nip=last_nip@entry=0x7fe32277fb78 <last_nip>, res=res@entry=1)
    at getnssent_r.c:139
#4  0x00007fe3226b82b3 in endhostent () at ../nss/getXXent_r.c:142
#5  0x00005558b13c8339 in hosts_keys (number=<optimized out>, key=<optimized out>) at getent.c:305
#6  0x00005558b13c7109 in main (argc=<optimized out>, argv=0x7ffcc666eab8) at getent.c:994
(gdb) frame 0
#0  0x00007fe322598301 in nss_host2ips_free_host_list (host_list=0x5558b332b8b0) at src/parser.c:45
45	            info_next = host_info->info_next;
```

**Comment by Cycatz** [comment]
It seems the error no longer occurs after recompling the library. Need more robust tests.
